name: Testing amplify

on:
  push:
    branch:
      - 'platelet_test'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Wait for Amplify to finish building
      uses: duckbytes/amplify-build-status@master
      with:
        app-id: ${{ secrets.AMPLIFY_APP_ID }}
        branch-name: ${{ github.ref_name }}
        commit-id: ${{ github.sha }}
        wait: true
        timeout: 100
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
